import { h, type App, type Component } from 'vue'
import {
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BringToFront,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Copy,
  Download,
  Edit,
  Eraser,
  File,
  FileImage,
  FileJson,
  FileText,
  Fullscreen,
  Github,
  Grid3X3,
  Group,
  HelpCircle,
  Highlighter,
  Image,
  Info,
  LayoutGrid,
  Link,
  List,
  ListOrdered,
  Lock,
  Maximize,
  Minus,
  MonitorPlay,
  MoreHorizontal,
  Move,
  Palette,
  Pause,
  PenTool,
  PieChart,
  Play,
  Plus,
  Presentation,
  Redo2,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Scissors,
  Search,
  SendToBack,
  Settings,
  Shapes,
  Sparkles,
  Square,
  SquareDashedBottom,
  Sticker,
  Table,
  TextCursor,
  Trash2,
  Type,
  Underline,
  Ungroup,
  Undo2,
  Volume2,
  VolumeX,
  X,
  ZoomIn,
  ZoomOut,
  Bold,
  Italic,
  Strikethrough,
  BarChart3,
  LineChart,
  ScatterChart,
  AreaChart,
} from 'lucide-vue-next'

export interface Icons {
  [key: string]: Component
}

const pick = (candidate?: Component): Component => candidate ?? Square

export const icons: Icons = {
  IconPlayOne: Play,
  IconFullScreenPlay: MonitorPlay,
  IconLock: Lock,
  IconUnlock: pick(Lock),
  IconPpt: Presentation,
  IconFormat: Settings,
  IconPicture: Image,
  IconFullScreen: Fullscreen,
  IconList: List,
  IconOrderedList: ListOrdered,
  IconFlipVertically: SquareDashedBottom,
  IconFlipHorizontally: SquareDashedBottom,
  IconFontSize: Type,
  IconCode: FileText,
  IconTextBold: Bold,
  IconTextItalic: Italic,
  IconTextUnderline: Underline,
  IconStrikethrough: Strikethrough,
  IconEdit: Edit,
  IconQuote: FileText,
  IconBackgroundColor: Palette,
  IconGroup: Group,
  IconUngroup: Ungroup,
  IconBack: ArrowLeft,
  IconNext: ArrowRight,
  IconFullwidth: Maximize,
  IconAlignTop: ArrowUp,
  IconAlignLeft: AlignLeft,
  IconAlignRight: AlignRight,
  IconAlignBottom: ArrowDown,
  IconAlignVertically: AlignCenter,
  IconAlignHorizontally: AlignCenter,
  IconBringToFront: BringToFront,
  IconSendToBack: SendToBack,
  IconSend: SendToBack,
  IconAlignTextLeft: AlignLeft,
  IconAlignTextRight: AlignRight,
  IconAlignTextCenter: AlignCenter,
  IconAlignTextBoth: AlignJustify,
  IconRowHeight: Grid3X3,
  IconWrite: PenTool,
  IconInsertTable: Table,
  IconAddText: Type,
  IconFill: Palette,
  IconTailoring: Scissors,
  IconEffects: Sparkles,
  IconColorFilter: Palette,
  IconUp: ChevronUp,
  IconDown: ChevronDown,
  IconPlus: Plus,
  IconMinus: Minus,
  IconConnection: Link,
  IconBringToFrontOne: BringToFront,
  IconSentToBack: SendToBack,
  IconGithub: Github,
  IconChartProportion: PieChart,
  IconChartHistogram: BarChart3,
  IconChartHistogramOne: BarChart3,
  IconChartLineArea: AreaChart,
  IconChartRing: PieChart,
  IconChartScatter: ScatterChart,
  IconChartLine: LineChart,
  IconChartPie: PieChart,
  IconRadarChart: AreaChart,
  IconText: Type,
  IconRotate: RotateCw,
  IconLeftTwo: ChevronLeft,
  IconRightTwo: ChevronRight,
  IconPlatte: Palette,
  IconClose: X,
  IconCloseSmall: X,
  IconUndo: Undo2,
  IconTransform: Move,
  IconClick: Circle,
  IconTheme: Palette,
  IconArrowCircleLeft: RotateCcw,
  IconArrowRight: ArrowRight,
  IconGraphicDesign: Shapes,
  IconLogout: X,
  IconErase: Eraser,
  IconClear: Trash2,
  IconAlignTextTopOne: ArrowUp,
  IconAlignTextBottomOne: ArrowDown,
  IconAlignTextMiddleOne: AlignCenter,
  IconPause: Pause,
  IconVolumeMute: VolumeX,
  IconVolumeNotice: Volume2,
  IconVolumeSmall: Volume2,
  IconVideoTwo: MonitorPlay,
  IconFormula: FileText,
  IconLinkOne: Link,
  IconFullScreenOne: Fullscreen,
  IconOffScreenOne: Fullscreen,
  IconPower: Circle,
  IconListView: LayoutGrid,
  IconMagic: Sparkles,
  IconHighLight: Highlighter,
  IconDownload: Download,
  IconIndentLeft: AlignLeft,
  IconIndentRight: AlignRight,
  IconVerticalSpacingBetweenItems: LayoutGrid,
  IconCopy: Copy,
  IconDelete: Trash2,
  IconSquare: Square,
  IconRound: Circle,
  IconNeedle: Circle,
  IconTextRotationNone: TextCursor,
  IconTextRotationDown: TextCursor,
  IconFormatBrush: Palette,
  IconPreviewOpen: MonitorPlay,
  IconPreviewClose: MonitorPlay,
  IconStopwatchStart: RefreshCw,
  IconSearch: Search,
  IconLeft: ArrowLeft,
  IconRight: ArrowRight,
  IconMoveOne: Move,
  IconHamburgerButton: MoreHorizontal,
  IconAttention: Info,
  IconCheckOne: Check,
  IconCheck: Check,
  IconCloseOne: X,
  IconInfo: Info,
  IconComment: FileText,
  IconUser: Circle,
  IconSwitch: RefreshCw,
  IconMore: MoreHorizontal,
  IconFilePdf: FileText,
  IconFileJpg: FileImage,
  IconNotes: FileText,
  IconRefresh: RefreshCw,
  IconHelpcenter: HelpCircle,
  IconMark: Sticker,
  IconCommand: Settings,
  IconSlideTwo: Presentation,
  IconSymbol: Shapes,
  IconWritingFluently: PenTool,
  IconUpload: File,
  IconScreenshotOne: Image,
}

const normalizeClass = (cls?: string) => {
  const base = 'realpptx-icon'
  if (!cls) return base
  return `${base} ${cls}`.trim()
}

const wrap = (component: Component) => {
  return {
    name: 'RealPPTXIconWrapper',
    props: {
      size: { type: [Number, String], default: 16 },
      color: { type: String, default: 'currentColor' },
      strokeWidth: { type: [Number, String], default: 2 },
    },
    setup(props: any, { attrs }: any) {
      return () => {
        const sanitized: Record<string, any> = {}
        for (const key in (attrs as any)) {
          if (key === 'theme' || key === 'color' || key === 'fill' || key === 'stroke') continue
          sanitized[key] = (attrs as any)[key]
        }

        return h(component as any, {
          ...sanitized,
          size: props.size,
          color: 'currentColor',
          strokeWidth: props.strokeWidth,
          class: normalizeClass((attrs as any).class),
        })
      }
    },
  }
}

export default {
  install(app: App) {
    Object.entries(icons).forEach(([name, component]) => {
      app.component(name, wrap(component))
    })
  },
}
